/*
 * @Descripttion:
 * @Author: zengyuanqiu
 * @Date: 2024-08-06 16:01:44
 * @LastEditors: zengyuanqiu
 * @LastEditTime: 2024-08-06 16:05:56
 */
export function onRequest(context) {
  console.log('美团订单')
  return new Response(
    JSON.stringify({
      code: 0,
      data: {
        pageCount: 1,
        totalCount: 1,
        wmOrderList: [
          {
            businessType: 1,
            commonInfo: {
              confirmTime: 1722926738,
              delivery_btime: 0,
              estimateArrivalTime: 1722928533,
              orderType: 0,
              order_time: 1722926723,
              order_time_fmt: '08-06 14:45',
              poiPushDay: 20240806,
              preOrderShowInTabTime: 0,
              refundType: -1,
              slaTag: 1,
              tabIndexes: [7, 11],
              version: 1722929524267,
              wmPoiId: 21525283,
              wmUserId: 3562384310,
              wm_order_id_view: 3301193203692215723,
              wm_poi_order_dayseq: 6,
            },
            orderInfo: {
              orderInfo: {
                groupBuyingVo: {
                  isShow: false,
                  groupBuyingDaySeqs: null,
                  groupBuyingTip: null,
                },
                dayseq: 5,
                wordLogo: '',
                statusDesc: '用户已收餐',
                expectTimeVo: {
                  expectPrefix: '立即送达',
                  expectTimeFmt: '08-06 12:43',
                  expectSuffix: '前送达',
                  expectType: '',
                  expectTimeBeforeModify: '',
                  expectTimeBeforeModifyTips: '',
                },
                onTimeInsuranceVo: null,
                userCancleInsuranceVo: {
                  effect: 1,
                  desc: '已保障',
                  status: 0,
                  name: '用户取消险',
                  claimDesc: '',
                },
                deliveryTimeoutDesc: '',
                orderTag: 0,
                tipInfoVo: {
                  tipType: 0,
                  tipDesc: null,
                  deadlineTime: 0,
                  isShow: false,
                },
                wmOrderViewId: '3801193040842826262',
                orderTimeFmt: '08-06 12:08',
                foodSafeEatInsuranceDesc: '',
                isShowConfirmAndCancelButton: false,
                isShowOrderCancelButton: false,
                isShowPartRefundButton: false,
                isShowDeliveryButton: false,
                isShowCustomerServiceIcon: true,
                isNeedTableware: true,
                poiName: '盐家铺·盐焗鸡（龙光城店）',
                cityName: null,
                copyButtonVo: {
                  isShow: true,
                  clickCopyContent:
                    '8月6日  #5号单#  盐家铺·盐焗鸡（龙光城店）  为保护顾客隐私，电话及地址已隐藏  【鸡鸭通吃】x1  合计：29.4元  备注:顾客需要餐具； (已付款)  在线支付订单',
                },
                printCount: 0,
                selfService: 0,
                basicVo: {
                  isPreOrder: false,
                  status: 8,
                  deliveryBtime: 0,
                  deliveryBtimeFmt: '',
                  isGroupOrder: false,
                  payStatus: 3,
                  orderTime: 1722917281,
                  estimateArrivalTime: 1722919390,
                  confirmTime: 1722917295,
                  payType: 2,
                  pickType: 0,
                  utime: 1722919188,
                  serverTime: 1722922529,
                  wmPoiId: 21525283,
                  isUavDelivery: false,
                  isSla: true,
                  wmOrderPayType: 2,
                  poiPushDay: 20240806,
                },
                wmOrderId: 2450713636986891,
                imReplyDefaultContent:
                  '亲爱的顾客，祝您用餐愉快，期待您下次再来我们店用餐。',
                jsdOrderInfoVo: {
                  isShow: false,
                  context: '',
                  mealNumber: '',
                },
                etaModifyVo: {
                  isShow: false,
                  uetaCtime: null,
                  etaTimeDate: null,
                  etaTimeDay: null,
                  wordLogo: null,
                  uetaTimeDate: null,
                  uetaTimeDay: null,
                  uetaWordLogo: null,
                  uetaModifyTimeGapDesc: null,
                  uetaModifyTimeGap: null,
                  uetaExpire: 0,
                  uetaStatus: 0,
                  agreeEtaModifyBtn: false,
                  refuseEtaModifyBtn: false,
                  isMoreThanOneDay: false,
                  etaModifyDescSuffix: null,
                },
                insuranceList: [
                  {
                    effect: 1,
                    desc: '已保障',
                    status: 0,
                    name: '用户取消险',
                    claimDesc: '',
                  },
                ],
                etaAutoAgreeTips: {
                  isShow: false,
                  desc: null,
                },
                isSharpShooter: false,
                orderCancelButtonVo: {
                  status: 0,
                  toastDesc: '',
                },
                sqtOrder: false,
                needSqtInvoice: false,
              },
              cansunInfo: null,
              chargeInfo: {
                fixedSettlementInfo: {
                  boxpriceTotal: 1.0,
                  foodAmount: 39.9,
                  discounts: [],
                  shippingFee: 3.6,
                  activityAmount: 11.0,
                  activityDetails: [
                    {
                      chargeAmount: '-3.0',
                      chargeDesc: '购买【鸡鸭通吃】原价38.9元现价35.9元',
                      isSharpShooter: false,
                    },
                    {
                      chargeAmount: '-3.0',
                      chargeDesc: '减配送费3.1元',
                      isSharpShooter: false,
                    },
                    {
                      chargeAmount: '-5.0',
                      chargeDesc: '用户使用了支付红包减8元',
                      isSharpShooter: false,
                    },
                  ],
                  formulaDisplayTitle: '',
                  formulaDisplay: '',
                  commisionAmount: 1.73,
                  offlineOrderSkPayAmount: 0.0,
                  shippingType: '2002',
                  commisionDetails: [
                    {
                      chargeAmount: '-1.73',
                      chargeDesc: '佣金',
                      isSharpShooter: false,
                    },
                  ],
                  userOnlinePayAfter: 0.0,
                  isDowngrade: false,
                  userPayTotalAmount: 29.4,
                  riderPayment: 0.0,
                  isRiderPay: false,
                  giftDetails: [],
                  userPayAmount: 0.0,
                  donateAmount: 0.01,
                  settleAmountDegrade: false,
                  packageBagMoney: 0.0,
                  orderSettleName: '预计收入',
                  orderSettleAmount: '21.67',
                  settleAmount: 21.67,
                  orderSettleDollar: true,
                  settleAmountInfo: '，预计收入￥21.67',
                  orderSettleWarning: {
                    isShow: false,
                    iconType: 0,
                    warningName: null,
                    warningReason: null,
                  },
                },
                settleDynamic: [
                  {
                    showRemind: true,
                    toast: '本单打包费为按商品收取',
                    chargeName: '打包费',
                    totalCharge: '￥1.0',
                    popupTotalChargeName: '合计',
                    popupTotalCharge: '￥1.0',
                    chargeRulesName: '',
                    item: [],
                    order: 0,
                    popupSubTitle: '',
                    popupTotalChargeExtension: '',
                    popupTotalChargeExtensionStyleId: 0,
                    chargeNameExtend: '',
                    chargeRulesType: 0,
                    calculationRules: '',
                    showRemindStyle: 0,
                    separateStyle: 0,
                    subSettleDynamicList: [],
                    popupTitle: '打包费',
                    appChargeRules: '',
                    pcChargeRules: '',
                    appStyleId: '1',
                    pcStyleId: '1',
                    chargeNameExtendIcon: 0,
                    tagList: [],
                    popupDiscountInfo: {
                      isShow: false,
                      popupDiscountTag: null,
                      disCountDesc: null,
                    },
                    popupBottomInfo: {
                      isShow: false,
                      isShowTagIcon: false,
                      isSharpShooter: false,
                      prefixMsg: null,
                      amountMsg: null,
                      suffixMsg: null,
                      markType: 0,
                      popupWindow: null,
                      appUrl: null,
                      pcUrl: null,
                    },
                    popupTotalChargeItems: [],
                    invoiceTip: '',
                  },
                  {
                    showRemind: true,
                    toast: '',
                    chargeName: '商家对顾客的活动补贴',
                    totalCharge: '-￥11.0',
                    popupTotalChargeName: '合计',
                    popupTotalCharge: '￥11.0',
                    chargeRulesName: '活动中心',
                    item: [
                      {
                        chargeDetailName:
                          '购买【鸡鸭通吃】原价38.9元现价35.9元',
                        chargeDetailMoney: '￥3.00',
                        item: [
                          {
                            chargeDetailName: '商家承担￥3.00，美团承担￥0.00',
                            chargeDetailMoney: '',
                            item: [],
                            styleId: 0,
                            showPopover: false,
                            popover: {
                              title: '',
                              content: '',
                              parsingRule: [],
                            },
                            isSharpShooter: false,
                          },
                        ],
                        styleId: 0,
                        showPopover: false,
                        popover: {
                          title: '',
                          content: '',
                          parsingRule: [],
                        },
                        isSharpShooter: false,
                      },
                      {
                        chargeDetailName: '减配送费3.1元',
                        chargeDetailMoney: '￥3.00',
                        item: [
                          {
                            chargeDetailName: '商家承担￥3.00，美团承担￥0.10',
                            chargeDetailMoney: '',
                            item: [],
                            styleId: 0,
                            showPopover: false,
                            popover: {
                              title: '',
                              content: '',
                              parsingRule: [],
                            },
                            isSharpShooter: false,
                          },
                        ],
                        styleId: 0,
                        showPopover: false,
                        popover: {
                          title: '',
                          content: '',
                          parsingRule: [],
                        },
                        isSharpShooter: false,
                      },
                      {
                        chargeDetailName: '用户使用了天天神券',
                        chargeDetailMoney: '￥5.00',
                        item: [
                          {
                            chargeDetailName: '商家承担￥5.00，美团承担￥3.00',
                            chargeDetailMoney: '',
                            item: [],
                            styleId: 0,
                            showPopover: false,
                            popover: {
                              title: '',
                              content: '',
                              parsingRule: [],
                            },
                            isSharpShooter: false,
                          },
                        ],
                        styleId: 0,
                        showPopover: true,
                        popover: {
                          title: '天天神券',
                          content:
                            '天天神券是指用户在天降、频道页等渠道获取的一种红包，通过标签、膨胀等功能吸引用户进店下单。该红包商家承担金额不超过报名活动时提报的额度。',
                          parsingRule: [
                            {
                              key: 'link',
                              name: '去设置>',
                              uri: '',
                            },
                          ],
                        },
                        isSharpShooter: false,
                      },
                    ],
                    order: 50,
                    popupSubTitle: '以下活动费用为商家自主为用户设置的活动补贴',
                    popupTotalChargeExtension: '',
                    popupTotalChargeExtensionStyleId: 0,
                    chargeNameExtend: '',
                    chargeRulesType: 1,
                    calculationRules: '',
                    showRemindStyle: 1,
                    separateStyle: 0,
                    subSettleDynamicList: [],
                    popupTitle: '商家对顾客的活动补贴',
                    appChargeRules:
                      'https://waimaieapp.meituan.com/igate/wmact/h5/index.html?footer=2',
                    pcChargeRules:
                      'https://waimaieapp.meituan.com/igate/wmact/pc/my.html',
                    appStyleId: '1',
                    pcStyleId: '1',
                    chargeNameExtendIcon: 0,
                    tagList: [],
                    popupDiscountInfo: {
                      isShow: false,
                      popupDiscountTag: null,
                      disCountDesc: null,
                    },
                    popupBottomInfo: {
                      isShow: false,
                      isShowTagIcon: false,
                      isSharpShooter: false,
                      prefixMsg: null,
                      amountMsg: null,
                      suffixMsg: null,
                      markType: 0,
                      popupWindow: null,
                      appUrl: null,
                      pcUrl: null,
                    },
                    popupTotalChargeItems: [],
                    invoiceTip: '',
                  },
                  {
                    showRemind: false,
                    toast: '',
                    chargeName: '商品优惠后金额',
                    totalCharge: '￥28.9',
                    popupTotalChargeName: '',
                    popupTotalCharge: '',
                    chargeRulesName: '',
                    item: [],
                    order: 51,
                    popupSubTitle: '',
                    popupTotalChargeExtension: '',
                    popupTotalChargeExtensionStyleId: 0,
                    chargeNameExtend: '',
                    chargeRulesType: 0,
                    calculationRules: '',
                    showRemindStyle: 0,
                    separateStyle: 1,
                    subSettleDynamicList: [],
                    popupTitle: '商品优惠后金额',
                    appChargeRules: '',
                    pcChargeRules: '',
                    appStyleId: '4',
                    pcStyleId: '5',
                    chargeNameExtendIcon: 0,
                    tagList: [],
                    popupDiscountInfo: {
                      isShow: false,
                      popupDiscountTag: null,
                      disCountDesc: null,
                    },
                    popupBottomInfo: {
                      isShow: false,
                      isShowTagIcon: false,
                      isSharpShooter: false,
                      prefixMsg: null,
                      amountMsg: null,
                      suffixMsg: null,
                      markType: 0,
                      popupWindow: null,
                      appUrl: null,
                      pcUrl: null,
                    },
                    popupTotalChargeItems: [],
                    invoiceTip: '',
                  },
                  {
                    showRemind: true,
                    toast:
                      '已加入青山公益行动，每单将捐赠一定金额至您指定的公益项目。具体项目详情请在门店设置-青山公益行动页面查看',
                    chargeName: '店铺环保捐赠',
                    totalCharge: '-￥0.01',
                    popupTotalChargeName: '合计',
                    popupTotalCharge: '￥0.01',
                    chargeRulesName: '',
                    item: [],
                    order: 52,
                    popupSubTitle: '',
                    popupTotalChargeExtension: '',
                    popupTotalChargeExtensionStyleId: 0,
                    chargeNameExtend: '',
                    chargeRulesType: 0,
                    calculationRules: '',
                    showRemindStyle: 0,
                    separateStyle: 0,
                    subSettleDynamicList: [],
                    popupTitle: '店铺环保捐赠',
                    appChargeRules: '',
                    pcChargeRules: '',
                    appStyleId: '1',
                    pcStyleId: '6',
                    chargeNameExtendIcon: 0,
                    tagList: [],
                    popupDiscountInfo: {
                      isShow: false,
                      popupDiscountTag: null,
                      disCountDesc: null,
                    },
                    popupBottomInfo: {
                      isShow: false,
                      isShowTagIcon: false,
                      isSharpShooter: false,
                      prefixMsg: null,
                      amountMsg: null,
                      suffixMsg: null,
                      markType: 0,
                      popupWindow: null,
                      appUrl: null,
                      pcUrl: null,
                    },
                    popupTotalChargeItems: [],
                    invoiceTip: '',
                  },
                  {
                    showRemind: true,
                    toast: '',
                    chargeName: '佣金(比例6.0%)',
                    totalCharge: '-￥1.73',
                    popupTotalChargeName: '合计',
                    popupTotalCharge: '￥1.73',
                    chargeRulesName: '',
                    item: [
                      {
                        chargeDetailName: '佣金',
                        chargeDetailMoney: '￥1.73',
                        item: [
                          {
                            chargeDetailName:
                              '佣金=（商品优惠后金额）* 6%，最低金额1.02元',
                            chargeDetailMoney: '',
                            item: [],
                            styleId: 0,
                            showPopover: false,
                            popover: {
                              title: '',
                              content: '',
                              parsingRule: [],
                            },
                            isSharpShooter: false,
                          },
                        ],
                        styleId: 0,
                        showPopover: false,
                        popover: {
                          title: '',
                          content: '',
                          parsingRule: [],
                        },
                        isSharpShooter: false,
                      },
                    ],
                    order: 60,
                    popupSubTitle:
                      '包括信息展示、交易结算、经营分析、客服咨询、系统维护等费用',
                    popupTotalChargeExtension: '',
                    popupTotalChargeExtensionStyleId: 0,
                    chargeNameExtend: '',
                    chargeRulesType: 0,
                    calculationRules: '',
                    showRemindStyle: 1,
                    separateStyle: 0,
                    subSettleDynamicList: [],
                    popupTitle: '佣金',
                    appChargeRules: '',
                    pcChargeRules: '',
                    appStyleId: '1',
                    pcStyleId: '6',
                    chargeNameExtendIcon: 0,
                    tagList: [],
                    popupDiscountInfo: {
                      isShow: false,
                      popupDiscountTag: null,
                      disCountDesc: null,
                    },
                    popupBottomInfo: {
                      isShow: false,
                      isShowTagIcon: false,
                      isSharpShooter: false,
                      prefixMsg: null,
                      amountMsg: null,
                      suffixMsg: null,
                      markType: 0,
                      popupWindow: null,
                      appUrl: null,
                      pcUrl: null,
                    },
                    popupTotalChargeItems: [],
                    invoiceTip: '',
                  },
                  {
                    showRemind: true,
                    toast: '',
                    chargeName: '配送服务费',
                    totalCharge: '-￥5.49',
                    popupTotalChargeName: '合计',
                    popupTotalCharge: '￥5.49',
                    chargeRulesName: '',
                    item: [
                      {
                        chargeDetailName: '距离收费(导航距离3.32公里)',
                        chargeDetailMoney: '￥3.96',
                        item: [
                          {
                            chargeDetailName: '0-2.5公里',
                            chargeDetailMoney: '￥2.7',
                            item: [],
                            styleId: 0,
                            showPopover: false,
                            popover: {
                              title: '',
                              content: '',
                              parsingRule: [],
                            },
                            isSharpShooter: false,
                          },
                          {
                            chargeDetailName: '2.5公里以上',
                            chargeDetailMoney: '￥1.26',
                            item: [],
                            styleId: 0,
                            showPopover: false,
                            popover: {
                              title: '',
                              content: '',
                              parsingRule: [],
                            },
                            isSharpShooter: false,
                          },
                        ],
                        styleId: 0,
                        showPopover: false,
                        popover: {
                          title: '',
                          content: '',
                          parsingRule: [],
                        },
                        isSharpShooter: false,
                      },
                      {
                        chargeDetailName: '价格收费(收费基数28.9元)',
                        chargeDetailMoney: '￥1.53',
                        item: [
                          {
                            chargeDetailName: '0-20元',
                            chargeDetailMoney: '￥0',
                            item: [],
                            styleId: 0,
                            showPopover: false,
                            popover: {
                              title: '',
                              content: '',
                              parsingRule: [],
                            },
                            isSharpShooter: false,
                          },
                          {
                            chargeDetailName: '20-30元区间',
                            chargeDetailMoney: '￥1.53',
                            item: [],
                            styleId: 0,
                            showPopover: false,
                            popover: {
                              title: '',
                              content: '',
                              parsingRule: [],
                            },
                            isSharpShooter: false,
                          },
                        ],
                        styleId: 0,
                        showPopover: false,
                        popover: {
                          title: '',
                          content: '',
                          parsingRule: [],
                        },
                        isSharpShooter: false,
                      },
                    ],
                    order: 60,
                    popupSubTitle:
                      '包括配送服务、骑手管理、配送客服咨询、配送系统建设及维护等费用（配送服务费受距离、时段等多因素影响，可能出现较大波动）',
                    popupTotalChargeExtension: '',
                    popupTotalChargeExtensionStyleId: 0,
                    chargeNameExtend: '长途配送，难度加大',
                    chargeRulesType: 0,
                    calculationRules: '配送服务费=距离收费+价格收费+时段收费',
                    showRemindStyle: 1,
                    separateStyle: 0,
                    subSettleDynamicList: [],
                    popupTitle: '配送服务费',
                    appChargeRules: '',
                    pcChargeRules: '',
                    appStyleId: '1',
                    pcStyleId: '6',
                    chargeNameExtendIcon: 0,
                    tagList: [],
                    popupDiscountInfo: {
                      isShow: false,
                      popupDiscountTag: null,
                      disCountDesc: null,
                    },
                    popupBottomInfo: {
                      isShow: false,
                      isShowTagIcon: false,
                      isSharpShooter: false,
                      prefixMsg: null,
                      amountMsg: null,
                      suffixMsg: null,
                      markType: 0,
                      popupWindow: null,
                      appUrl: null,
                      pcUrl: null,
                    },
                    popupTotalChargeItems: [],
                    invoiceTip: '',
                  },
                  {
                    showRemind: false,
                    toast: '',
                    chargeName: '预计收入',
                    totalCharge: '￥21.67',
                    popupTotalChargeName: '合计',
                    popupTotalCharge: '￥21.67',
                    chargeRulesName: '',
                    item: [],
                    order: 70,
                    popupSubTitle: '',
                    popupTotalChargeExtension: '',
                    popupTotalChargeExtensionStyleId: 0,
                    chargeNameExtend: '',
                    chargeRulesType: 0,
                    calculationRules: '',
                    showRemindStyle: 0,
                    separateStyle: 0,
                    subSettleDynamicList: [],
                    popupTitle: '预计收入',
                    appChargeRules: '',
                    pcChargeRules: '',
                    appStyleId: '2',
                    pcStyleId: '2',
                    chargeNameExtendIcon: 0,
                    tagList: [],
                    popupDiscountInfo: {
                      isShow: false,
                      popupDiscountTag: null,
                      disCountDesc: null,
                    },
                    popupBottomInfo: {
                      isShow: false,
                      isShowTagIcon: false,
                      isSharpShooter: false,
                      prefixMsg: null,
                      amountMsg: null,
                      suffixMsg: null,
                      markType: 0,
                      popupWindow: null,
                      appUrl: null,
                      pcUrl: null,
                    },
                    popupTotalChargeItems: [],
                    invoiceTip: '',
                  },
                  {
                    showRemind: false,
                    toast: '',
                    chargeName:
                      '预计收入=商品优惠后金额-店铺环保捐赠-佣金及配送服务费',
                    totalCharge: '',
                    popupTotalChargeName: '',
                    popupTotalCharge: '',
                    chargeRulesName: '',
                    item: [],
                    order: 72,
                    popupSubTitle: '',
                    popupTotalChargeExtension: '',
                    popupTotalChargeExtensionStyleId: 0,
                    chargeNameExtend: '',
                    chargeRulesType: 0,
                    calculationRules: '',
                    showRemindStyle: 0,
                    separateStyle: 0,
                    subSettleDynamicList: [],
                    popupTitle: '预计收入=商品优惠后金额',
                    appChargeRules: '',
                    pcChargeRules: '',
                    appStyleId: '5',
                    pcStyleId: '7',
                    chargeNameExtendIcon: 0,
                    tagList: [],
                    popupDiscountInfo: {
                      isShow: false,
                      popupDiscountTag: null,
                      disCountDesc: null,
                    },
                    popupBottomInfo: {
                      isShow: false,
                      isShowTagIcon: false,
                      isSharpShooter: false,
                      prefixMsg: null,
                      amountMsg: null,
                      suffixMsg: null,
                      markType: 0,
                      popupWindow: null,
                      appUrl: null,
                      pcUrl: null,
                    },
                    popupTotalChargeItems: [],
                    invoiceTip: '',
                  },
                  {
                    showRemind: true,
                    toast: '',
                    chargeName: '顾客实际支付',
                    totalCharge: '',
                    popupTotalChargeName: '合计',
                    popupTotalCharge: '￥29.4',
                    chargeRulesName: '',
                    item: [
                      {
                        chargeDetailName: '商品优惠后金额',
                        chargeDetailMoney: '￥28.9',
                        item: [
                          {
                            chargeDetailName:
                              '若商家设置了减配活动，则商品优惠后金额中已扣除本单减配活动的优惠金额',
                            chargeDetailMoney: null,
                            item: [],
                            styleId: 0,
                            showPopover: false,
                            popover: {
                              title: '',
                              content: '',
                              parsingRule: [],
                            },
                            isSharpShooter: false,
                          },
                        ],
                        styleId: 0,
                        showPopover: false,
                        popover: {
                          title: '',
                          content: '',
                          parsingRule: [],
                        },
                        isSharpShooter: false,
                      },
                      {
                        chargeDetailName: '顾客配送费(优惠前)',
                        chargeDetailMoney: '￥3.6',
                        item: [],
                        styleId: 0,
                        showPopover: false,
                        popover: {
                          title: '',
                          content: '',
                          parsingRule: [],
                        },
                        isSharpShooter: false,
                      },
                      {
                        chargeDetailName: '平台活动补贴（含合作商、第三方）',
                        chargeDetailMoney: '-￥3.10',
                        item: [
                          {
                            chargeDetailName:
                              '减配送费3.1元（平台补贴￥0.10 ）',
                            chargeDetailMoney: '-￥0.10',
                            item: null,
                            styleId: 0,
                            showPopover: false,
                            popover: {
                              title: '',
                              content: '',
                              parsingRule: [],
                            },
                            isSharpShooter: false,
                          },
                          {
                            chargeDetailName:
                              '用户使用了天天神券（平台补贴￥3.00 ）',
                            chargeDetailMoney: '-￥3.00',
                            item: null,
                            styleId: 0,
                            showPopover: false,
                            popover: {
                              title: '',
                              content: '',
                              parsingRule: [],
                            },
                            isSharpShooter: false,
                          },
                        ],
                        styleId: 0,
                        showPopover: false,
                        popover: {
                          title: '',
                          content: '',
                          parsingRule: [],
                        },
                        isSharpShooter: false,
                      },
                    ],
                    order: 80,
                    popupSubTitle: '',
                    popupTotalChargeExtension: '',
                    popupTotalChargeExtensionStyleId: 0,
                    chargeNameExtend: '',
                    chargeRulesType: 0,
                    calculationRules:
                      '顾客实际支付=商品优惠后金额+顾客配送费(优惠前)-平台活动补贴',
                    showRemindStyle: 1,
                    separateStyle: 0,
                    subSettleDynamicList: [],
                    popupTitle: '顾客实际支付',
                    appChargeRules: '',
                    pcChargeRules: '',
                    appStyleId: '3',
                    pcStyleId: '4',
                    chargeNameExtendIcon: 0,
                    tagList: [],
                    popupDiscountInfo: {
                      isShow: false,
                      popupDiscountTag: null,
                      disCountDesc: null,
                    },
                    popupBottomInfo: {
                      isShow: false,
                      isShowTagIcon: false,
                      isSharpShooter: false,
                      prefixMsg: null,
                      amountMsg: null,
                      suffixMsg: null,
                      markType: 0,
                      popupWindow: null,
                      appUrl: null,
                      pcUrl: null,
                    },
                    popupTotalChargeItems: [],
                    invoiceTip: '查看应向用户开具发票的金额',
                  },
                ],
              },
              foodInfo: {
                remark: '顾客需要餐具；',
                invoiceTitle: '',
                invoiceTaxpayerId: '',
                foodKindsAndNum: '1种商品，共1件',
                cartDetailVos: [
                  {
                    cartName: '1号口袋',
                    details: [
                      {
                        foodName: '【鸡鸭通吃】',
                        foodPrice: 35.9,
                        count: 1,
                        originFoodPrice: 38.9,
                        discountPoint: '9.2折',
                        cartId: 0,
                        foodId: 23270369916,
                        detailId: '7706966233931',
                        subDetails: [],
                        isSharpShooter: false,
                      },
                    ],
                  },
                ],
                userLabelVo: {
                  isShow: true,
                  contents: [
                    {
                      type: 17,
                      info: '下单3次',
                    },
                    {
                      type: 16,
                      info: '收藏店铺',
                    },
                  ],
                },
                customerRemark: '有备注',
              },
              userCompensateInfo: {
                title: '',
                time: '',
                moneyDesc: '',
                reasonDesc: null,
                pictures: [],
                appealInfoVo: {
                  isShow: false,
                  desc: null,
                  appealInfo: null,
                },
                isShow: false,
                compensateRules: null,
                applyBtnRefreshTime: 0,
                applyEntranceGray: false,
                sortSecond: 0,
              },
              logisticsInfo: {
                isShow: true,
                basicVo: {
                  status: 40,
                  fetchTime: 1722917781,
                  dispatcherVo: {
                    name: '蒋杰',
                    mobile: '19841992825',
                    icon: 'https://waimaieapi.meituan.com/static/imgs/logostics/qishouicon.png',
                    role: '配送员',
                    type: -1,
                    typeName: '',
                  },
                  dispatchOrderId: '9362611049609',
                  code: '2002',
                  type: 1,
                  assignTime: 1722917572,
                  supportUnionDispatcher: false,
                  defaultPushType: 101,
                  id: 101,
                  sendTime: 1722917296,
                  deliveryPushType: 101,
                  ifSelfLogistics: false,
                  isZbDispatcher: false,
                  animationType: -1,
                  ifSupportNoDispatcherGray: true,
                },
                title: '蒋杰',
                tagVo: {
                  isShow: true,
                  name: '美团骑手',
                  isCanClick: false,
                  subName: '',
                  styleType: 0,
                },
                timerVo: {
                  isShow: false,
                  serverTime: -1,
                  isLogisticsAbnormal: false,
                },
                phoneIconVo: {
                  isShow: true,
                  isInvalidOrder: true,
                  privacyOutOfTime: 1723003681,
                  content: '查看骑手电话',
                },
                isShowLocationIcon: true,
                warningTipVo: {
                  isShow: false,
                  desc: '',
                  detail: '',
                  slowOrderPressureInfo: '',
                  preOrderPressureInfo: '',
                  logisticsAbnormal: false,
                  exceptionType: 0,
                  resendShippAfterInterventionInfo: {
                    countDown: {
                      show: false,
                      resendShippTime: 0,
                      text: null,
                    },
                    rejectButton: {
                      show: false,
                      text: null,
                      dialogTitle: null,
                      dialogContent: null,
                    },
                    agreeButton: {
                      show: false,
                      text: null,
                      dialogTitle: null,
                      dialogContent: null,
                    },
                    show: false,
                    type: -1,
                    showContent: null,
                  },
                  descTips: null,
                  completeMealPressureInfo: '',
                  suggestOperationRemindInfo: null,
                  suggestButton: null,
                },
                uavDeliveryTip: '',
                logisticsProcessVo: {
                  isShow: true,
                  formatTime: '12:39',
                  processDesc: '订单已送达',
                  isShowDetail: true,
                },
                preOrderPressureInfo: '',
                delayPushVo: {
                  isShow: false,
                  delayPushTitle: '',
                  delayPushMin: -1,
                  unit: '',
                },
                logisticsRightVo: {
                  rightsIcon: '',
                  rightsContent: '',
                  rightsColor: '',
                  rightsBgColor: '',
                  rightValid: false,
                },
                addFeeVo: {
                  isShow: false,
                  title: '',
                  tipFee: 0.0,
                  unit: '',
                  isShowTryButton: true,
                },
                deliveryFeeVo: {
                  isShow: false,
                  title: '',
                  payAmount: 0.0,
                  unit: '',
                  tipFee: 0.0,
                  couponAmount: 0.0,
                  payType: '',
                  isShowDeliveryFeeDetail: false,
                  pricingDetails: [],
                  bmlAmount: 0.0,
                },
                riderExpectAcceptTimeVo: {
                  isShow: false,
                  riderExpectAcceptTime: 0,
                  riderEATLimit: 0,
                  hasRiderPressure: false,
                  riderExpectAcceptText: null,
                },
                urgeFoodButtonVo: {
                  isShow: false,
                  buttonStatus: 0,
                  riderHasChanged: false,
                  availableTime: 0,
                  mtDispatch: false,
                  content: null,
                  displayToast: null,
                },
                reportExceptionButtonVo: {
                  isShow: false,
                  content: '',
                },
                evaluateRiderButtonVo: {
                  isShow: true,
                  content: '评价骑手',
                  buttonType: 1,
                  iconType: 1,
                  orderType: 0,
                },
                changeSelfLogisticsButtonVo: {
                  isShow: false,
                  content: '',
                  displayType: 0,
                  displayToast: null,
                  flexibleSelfLogisticsGray: false,
                  flexibleSelfRuleId: 0,
                },
                cancelLogisticsButtonVo: {
                  isShow: false,
                  content: '',
                  dispatchCancelIsLock: false,
                  dispatchCancelLockTime: 0,
                  isQikeThirdDistributor: false,
                },
                addFeeButtonVo: {
                  isShow: false,
                  content: null,
                  log: 'lgsstat_40_5',
                },
                sendDistributionButtonsVo: {
                  isShow: false,
                  distributorList: [],
                  lastUse: {
                    logisticsId: 0,
                    logisticsCode: null,
                    logisticsName: null,
                    logisticsType: 0,
                    priority: 0,
                    specificLogisticsId: 0,
                    specificLogisticsCode: null,
                    carrierCode: null,
                    carrierName: null,
                    carrierConnectLogisticsName: null,
                    smallMarkType: 0,
                    displayType: 0,
                    zbLogisticsCodes: null,
                    displayToast: null,
                  },
                  thirdDispatchAsyncTime: 3,
                  zbResourceInfo: {
                    startTime: 0,
                    endTime: 0,
                    picUrl: '',
                    type: 0,
                  },
                  zbResourceInfoListAndRights: null,
                  zbPreviewVersion: 0,
                },
                riderExpectedDeliveryVo: {
                  isShow: false,
                  riderDeliveredStartTime: 0,
                  riderDeliveredEndTime: 0,
                },
                distributionDetailVo: {
                  riderDesc: '骑手：蒋杰',
                  showRiderLocationButton: true,
                  showPhoneButton: true,
                  showCommentButton: true,
                },
                dispatcherLessReason: '',
                noDispatcherPreConfirmEntry: '',
                isNewTipFee: true,
                orderLogisticDetailBtnVo: {
                  isShow: false,
                  content: '',
                },
                moreLogisticsButtonVo: {
                  isShow: false,
                  content: '',
                },
                moreLogisticsTagVo: {
                  isShow: false,
                  content: '',
                },
                changeRiderButtonVo: {
                  isShow: false,
                  content: null,
                  displayType: 0,
                  displayToast: null,
                  availableTime: 0,
                },
                manageExpectationsVo: {
                  isShow: false,
                  currentMessage: null,
                  allMessages: null,
                },
                customerServiceButtonVo: null,
              },
              mealAbnormalInfo: {
                appealInfoVo: {
                  isShow: false,
                  appealWarningType: 0,
                  appealWarningContentVo: {
                    appAppealWarningContent: '',
                    pcAppealWarningContent: '',
                  },
                  appealTimeoutVo: {
                    isShow: false,
                    appealTimeout: 360,
                  },
                  appealGuideVo: {
                    isToShow: false,
                    appealTimeLimit: 360,
                  },
                  appealButtonVo: {
                    isToShow: false,
                    appealTimeLimit: 360,
                    riderNoticeMealSlowTime: 0,
                    appealTimeout: 360,
                  },
                },
                appealRecordVo: {
                  isShow: false,
                  appealRecords: [],
                },
                mealAbnormalBasicVo: {
                  orderAppealStatus: 0,
                  sendoutExSign: 0,
                },
              },
              mealInfo: {
                foodDoneTitleVo: {
                  isChange: false,
                  title: '已上报出餐完成，出餐用时 ',
                  changeTitle: null,
                  reminderTime: 0,
                },
                countDownTimerVo: {
                  isShowVo: {
                    isToShow: true,
                    preRemindTime: -3597,
                  },
                  timerShowVo: {
                    isFoodDone: true,
                    preMealTimeIntervalFmt: '00:04:06',
                    preMealBeginTime: 1722917295,
                    preMealEndTime: 1722918495,
                  },
                },
                foodDoneTip: '',
                foodDoneButtonVo: {
                  isShow: false,
                  buttonName: null,
                  buttonFoldName: null,
                  onButtonTip: null,
                  buttonClickVo: null,
                },
                foodSendDeviceInfo: '',
                isShow: true,
                mealTipInfoVo: {
                  tipType: 0,
                  tipDescVo: null,
                  deadlineTime: 0,
                  isToShow: false,
                },
                runLegVo: {
                  isShow: false,
                  runLegTitleVo: null,
                  runLegTimerVo: null,
                  runLegTipVo: null,
                  runLegButtonVo: null,
                },
                mealBasicVo: {
                  fetchTime: 1722917781,
                  foodDoneTime: 1722917541,
                  preReminderTime: 60,
                  isFoodDone: true,
                  preReminderType: 1,
                  selfReportMealOrder: false,
                  preOrderShowInTabTime: 0,
                },
                version: 0,
                foodDoneExamineVo: null,
              },
              refundInfo: {
                refundSuggestionVo: {
                  isShow: false,
                  refundSuggestions: null,
                },
                refundRecords: [],
                saleSchedules: [],
                showInsuranceAdvice: false,
                preResponsibilityReasonVo: {
                  isShow: false,
                  title: null,
                },
                preResponsibilityButtonVo: {
                  isShow: false,
                  title: null,
                },
                showInsuranceAdviceDesc: '',
                preResponsibleParty: 0,
                isSaleInfoGray: true,
                refundBasicVo: {
                  isPartRefundApply: false,
                  refundType: -1,
                },
                insuranceAdviceSuggestVo: {
                  tag: null,
                  title: null,
                  detail: null,
                  linkName: null,
                  linkUrl: null,
                  isShow: false,
                },
                isNewCansun: false,
                afterSaleIssueGray: true,
                sortSecond: 0,
                refundBlockVersion: 1,
                instantRefundJudgeInfo: {
                  title: '',
                  isShow: false,
                  afterSaleId: 0,
                  subTitle: '',
                  timestamp: 0,
                  content: [],
                  billTime: 0,
                },
                waitingRefundVo: null,
                majorDisputeAuditInfo: null,
              },
              reminderInfo: null,
              responsibleInfo: {
                responsibleInfos: [],
                responsibleAppealVo: {
                  isCanAppeal: false,
                  deadlineTime: 0,
                  canAppealDesc: null,
                  canNotAppealDesc: null,
                },
                viewBillButtonVo: {
                  isShow: false,
                  context: null,
                  periodType: 0,
                  periodId: null,
                  isUserResponsible: false,
                  userResponsibleTime: 0,
                },
                responsibleLinkTip: null,
              },
              userInfo: {
                wmUserId: 134967535,
                recipientName: '徐先生',
                recipientPhoneVo: {
                  appRecipientPhoneVo: {
                    isCanClick: true,
                    recipientPhoneShow: '手机尾号5071',
                  },
                  pcRecipientPhoneVo: {
                    pcPhoneVos: [
                      {
                        title: '隐私号码',
                        phones: [''],
                        encrypted: 0,
                        clickShowPhoneButtonVo: {
                          isShow: true,
                          showPhoneKey: 'Privacy_Phone',
                        },
                      },
                      {
                        title: '备用号码',
                        phones: [''],
                        encrypted: 0,
                        clickShowPhoneButtonVo: {
                          isShow: true,
                          showPhoneKey: 'Backup_Privacy_Phones',
                        },
                      },
                      {
                        title: '顾客电话',
                        phones: ['手机尾号5071'],
                        encrypted: 0,
                        clickShowPhoneButtonVo: {
                          isShow: false,
                          showPhoneKey: 'Recipient_Phone',
                        },
                      },
                    ],
                  },
                },
                phoneIconShowVo: {
                  isToShow: true,
                  isOrderCondition: true,
                  compareTime: 1723005588,
                },
                recipientPhoneTipVo: {
                  isShow: true,
                  phoneType: 1,
                  tipDesc:
                    '为保证服务体验，您在拨打或者接听隐私号电话时，可能会被录音',
                },
                isShowIMIcon: true,
                customerAddressVo: {
                  isShow: true,
                  recipientAddressVo: {
                    appRecipientAddressVo: {
                      recipientAddress: '',
                    },
                    pcRecipientAddressVo: {
                      isHide: true,
                      recipientAddress: '',
                    },
                  },
                  isShowMap: true,
                  distanceAndAddressVo: {
                    inArea: 1,
                    addressLatitude: 22708765,
                    addressLongitude: 114404276,
                    poiLatitude: 22728437,
                    poiLongitude: 114417129,
                    orderDistance: 3320.0,
                  },
                },
                customerRemarkVo: {
                  foodDoneInfo: '出餐已确认',
                  logisticsInfo: '',
                },
              },
              foodSafeInfos: [],
            },
          },
        ],
      },
    })
  )
}
